### ISSUE TITLE
Support plotting with Bokeh / Plot.ly

### ISSUE THREAD

**Issue by 0liu** [emacs-jupyter/jupyter#310]
When plotting with Bokeh or Plot.ly  a warning issued:

`Warning (jupyter): :display-data did not return requested mimetype(s): (:text/org :image/svg+xml :image/jpeg :image/png :text/markdown :text/latex :text/plain)`

I guess ob-jupyter does not support javascript return as in #53 ? Is it possible to make it happen? Interactive plotting would be super useful.

**Comment by lccambiaghi** [comment]
If you are happy to render plotly in the browser, you can set:
```
import plotly.io as pio
pio.renderers.default = "browser"
```

**Comment by 0liu** [comment]
> If you are happy to render plotly in the browser, you can set:
> 
> ```
> import plotly.io as pio
> pio.renderers.default = "browser"
> ```

Thank you! This works, while the output and code are separate and not bound together as in notebook. It's more like using ipython directly.
