### ISSUE TITLE
Julia default environment activated for non-default environment kernel

### ISSUE THREAD

**Issue by fleimgruber** [emacs-jupyter/jupyter#437]
Given a kernel installed from an activated Julia environment (`julia --project=@.`), evaluating this inside an org-mode Julia code block:

```julia
using Pkg

Pkg.status()
```

returns

```
Status `~/.julia/environments/v1.8/Project.toml`
 [0c46a032] DifferentialEquations v7.7.0
 ...
```

that is the Julia jupyter process has activated the default environment, not the env from which the kernel was installed (`Pkg.build("IJulia")` from an activated Julia REPL). This is still the case after removing the jupyter kernelspec from `~/.local/share/jupyter/kernels` that was installed from the default environment.

For Python the correct virtual environment is loaded for each kernel because the environments have different Python executables each. For Julia the executable is mostly the same for all environments. Do I miss something in the docs or how is Julia environment selection handled / supposed to happen in emacs-jupyter?

**Comment by jrbp** [comment]
I suspect this isn't an emacs-jupyter issue.

By default IJulia installs a kernel that will [use the project in the notebook directory](https://julialang.github.io/IJulia.jl/stable/manual/usage/#Julia-projects). So if there isn't a Project.toml in your org file directory it ends up just using the default environment. If you want to install a kernel that always uses a particular project environment you can do:

```julia
using IJulia
installkernel("your_kernel_name", "--project=path/to/project")
```

**Comment by fleimgruber** [comment]
Thanks for your reply, link and snippet @jrbp, that works!
