### ISSUE TITLE
Execute org src block in REPL for IPDB debugging 

### ISSUE THREAD

**Issue by struan-robertson** [emacs-jupyter/jupyter#444]
I'm probably missing something obvious but how can you send the code in the current source block to be executed in a REPL? I can open the session REPL with C-c C-v C-z but see no way other than manually typing each line.

This is for the purpose of debugging with IPDB, as having the debug output to a #+RESULTS: block is not ideal. If there is a better way of doing this please let me know.

Thanks.

**Comment by nnicandro** [comment]
You can use `C-c C-v C-l` (`org-babel-load-in-session`) to load the body of the code block into the REPL session.
