### ISSUE TITLE
New kernel not recognised until Emacs restarted

### ISSUE THREAD

**Issue by fast-90** [emacs-jupyter/jupyter#447]
Probably (hopefully) an easy question, but I couldn't find the answer by searching.

Whenever I add a new jupyter kernel (e.g. via `python -m ipykernel install --user --name=MyEnv`), the new `MyEnv` environment is not recognised by emacs-jupyter until I restart Emacs. For example, the kernel is not in the available list if I run `jupyter-run-repl`, nor does running a cell in org-mode work with `:kernel MyEnv` in the header (until I restart Emacs). If I try to do the latter, it says `no valid kernelspec for kernel name`.

Is there any way to make emacs-jupyter recognise the newly created kernel without restarting Emacs?

**Comment by fast-90** [comment]
> I would check the PATH variable before and after restarting the emacs. If the python you are using changes during run time as opposed to your system one.

I just tried this with a new test env again, and as far as I can tell my PATH variable is the same before and after restarting. The new kernels are also located in the same folder as the other existing kernels, so I don't think that's it.

**Comment by nnicandro** [comment]
You can run `M-: (org-babel-jupyter-aliases-from-kernelspecs t)` to update the kernelspecs seen by Org and `jupyter-run-repl`.
