### ISSUE TITLE
Anyone able to make emacs-jupyter work on a Apple Silicon Mac ?

### ISSUE THREAD

**Issue by ltmsyvag** [emacs-jupyter/jupyter#452]
update: 

I was later able to build the emacs-zmq.so with a clean reinstall of the emacs-zmq package, then I was able to use emacs-jupyter in org mode. This issue is thus closed. 

----

The org source block and REPL worked like a charm for me when I used an intel Mac, but I can't get it to work on my Apple Silicon Mac. 

It seems that the problem is about the emacs-zmq package. I don't know much about it, but I do know that I need an `emacs-zmq.so` or `.dylib` in that package folder (can be either suffix, it doesn't matter). When I used my intel Mac, I just had this file, I cannot remember how it got there, because it does not come with the emacs-zmq package install. It was probably downloaded from the [releases](https://github.com/nnicandro/emacs-zmq/releases) of emacs-zmq, where they offer the `emacs-zmq.so` file for x86_64, the intel architecture. But now the new Macs have the architecture of arm64, so they cannot use this `.so` file.

I also failed at my attempt to `make` my own `.so` file from source, which seemed prohibitively hard for someone who had never done it before. Related discussions are very few on google. To a non-tech-savvy guy like me, the dependency on emacs-zmq could pretty much be considered broken for Apple Silicon Macs. 

So at this point I just hope to know if anyone succeeded at using emacs-jupyter source blocks on an Apple Silicon Mac, if so, I would appreciate that you share the experience.

**Comment by djliden** [comment]
Thanks, reinstalling the package solved the issue for me as well.
