### ISSUE TITLE
Jupyter generates many compile warnings

### ISSUE THREAD

**Issue by danielpopescu** [emacs-jupyter/jupyter#459]
Using 29.0.91 native-comp version, I get a lot of warnings (two other packages, out of hundreds) issue, each ,one single warning...
(note that I had a fair number of warnings with 29.0.90 without native-comp as well, just as many.)... It is unusual (I do not see any real issue though) to see these many warnings when so many other packages have zero...

.emacs.d/elpa/jupyter-20230510.1523/jupyter-base.el: Warning: Non-symbol arguments to cl-defgeneric: (obj jupyter-finalized-object)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-messages.el: Warning: Unknown type: json-plist [10 times]
.emacs.d/elpa/jupyter-20230510.1523/jupyter-comm-layer.el: Warning: Non-symbol arguments to cl-defgeneric: (comm jupyter-comm-layer) [8 times]
.emacs.d/elpa/jupyter-20230510.1523/jupyter-mime.el: Warning: Non-symbol arguments to cl-defgeneric: (display-id string)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Unknown type: json-plist
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Non-symbol arguments to cl-defgeneric: (_client jupyter-kernel-client) [2 times]
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Non-symbol arguments to cl-defgeneric: (client jupyter-kernel-client)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Non-symbol arguments to cl-defgeneric: (client jupyter-kernel-client)(inhibit-handlers nil)(code nil)(silent nil)(store-history t)(user-expressions nil)(allow-stdin (jupyter-channel-alive-p client :stdin))(stop-on-error nil)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Non-symbol arguments to cl-defgeneric: (source symbol)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Non-symbol arguments to cl-defgeneric: (client jupyter-kernel-client)(inhibit-handlers nil)(code nil)(pos 0)(detail 0)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Non-symbol arguments to cl-defgeneric: (client jupyter-kernel-client)(inhibit-handlers nil)(code nil)(pos 0)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Non-symbol arguments to cl-defgeneric: (client jupyter-kernel-client)(inhibit-handlers nil)(output nil)(raw nil)(hist-access-type "tail")(session nil)(start nil)(stop nil)(n 10)(pattern nil)(unique nil)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Non-symbol arguments to cl-defgeneric: (client jupyter-kernel-client)(inhibit-handlers nil)(code nil)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Non-symbol arguments to cl-defgeneric: (client jupyter-kernel-client)(inhibit-handlers nil)(target-name nil)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Non-symbol arguments to cl-defgeneric: (client jupyter-kernel-client)(inhibit-handlers nil)(id nil)(target-name nil)(data nil)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Non-symbol arguments to cl-defgeneric: (client jupyter-kernel-client)(inhibit-handlers nil)(id nil)(data nil) [2 times]
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Non-symbol arguments to cl-defgeneric: (client jupyter-kernel-client)(inhibit-handlers nil)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-client.el: Warning: Non-symbol arguments to cl-defgeneric: (client jupyter-kernel-client)(inhibit-handlers nil)(restart nil)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-channel.el: Warning: Non-symbol arguments to cl-defgeneric: (channel jupyter-channel) [3 times]
.emacs.d/elpa/jupyter-20230510.1523/jupyter-kernel-manager.el: Warning: Non-symbol arguments to cl-defgeneric: (kernel jupyter-kernel-lifetime) [4 times]
.emacs.d/elpa/jupyter-20230510.1523/jupyter-kernel-manager.el: Warning: Non-symbol arguments to cl-defgeneric: (manager jupyter-kernel-manager) [3 times]
.emacs.d/elpa/jupyter-20230510.1523/jupyter-repl.el: Warning: Non-symbol arguments to cl-defgeneric: (client jupyter-repl-client)
.emacs.d/elpa/jupyter-20230510.1523/ob-jupyter.el: Warning: Non-symbol arguments to cl-defgeneric: (session string)
.emacs.d/elpa/jupyter-20230510.1523/ob-jupyter.el: Warning: Non-symbol arguments to cl-defgeneric: (_session org-babel-jupyter-session)
.emacs.d/elpa/jupyter-20230510.1523/jupyter-rest-api.el: Warning: Non-symbol arguments to cl-defgeneric: (client jupyter-rest-client) [6 times]
Loading .emacs.d/elpa/zmq-20230515.1736/emacs-zmq (module)...done
.emacs.d/elpa/jupyter-20230510.1523/jupyter-ioloop.el: Warning: Non-symbol arguments to cl-defgeneric: (ioloop jupyter-ioloop) [3 times]

**Comment by nnicandro** [comment]
Fixed by 7d7cf4716bf0dcd3e054c1ca89c89db5221a1c5b and surrounding commits.
