### ISSUE TITLE
require: Symbol’s value as variable is void: jupyter-channel

### ISSUE THREAD

**Issue by danielpopescu** [emacs-jupyter/jupyter#463]
whenever executing a python code block... this is with the latest code (June 8)...

Emacs 29/native compilation/macos

**Comment by zhenwu0728** [comment]
Same issue here. Emacs 28.2/native compilation/macos

**Comment by fast-90** [comment]
Same here, Emacs 29.0.91/native compilation/MacOS. I tried it with `emacs -Q` as well.

**Comment by IsakFalk** [comment]
I have the same issue, Emacs 29.0.91 with native compilation (Specific Arch package: https://aur.archlinux.org/packages/emacs29-git) on Arch linux.

**Comment by akirakyle** [comment]
To temporarily work around this issue until the bytecomp errors are fixed (which I'm guessing are what result in the actual error), you can set the following to disable native comp for this package:

```emacs-lisp
(setq native-comp-jit-compilation-deny-list '("jupyter.*.el"))
```

**Comment by danielpopescu** [comment]
Thank you! In fact, one can do a bit better: (setq native-comp-jit-compilation-deny-list '("jupyter-channel.*.el"))

**Comment by torfjelde** [comment]
Also same issue; also addressed it by disabling native-comp

**Comment by torfjelde** [comment]
#472 fixes the issue on m end:)
