### ISSUE TITLE
strange characters in the output when there's errors

### ISSUE THREAD

**Issue by yitang** [emacs-jupyter/jupyter#465]
Thanks for providing this useful package that enables me to stick with org-mode.

I'm having one small issue I started to see when using emacs-jupyter but it might not relate to it at all.

as the below screenshot shows, there are some strange characters, "^[[0;32m" for example, in the output block. it only happens when there's error. 
![image](https://github.com/emacs-jupyter/jupyter/assets/6054101/5c880fb2-28e9-40ba-8d6b-0dede9f1a62c)

what's the possible causes of it? and how to keep the error message clean and useful? 

Thanks,

**Comment by Panadestein** [comment]
I had a similar problem, and fixed it with this org-mode hook:

```emacs-lisp
(use-package org
  :straight t
  :init
  (defun display-ansi-colors ()
    "Fixes kernel output in emacs-jupyter"
    (ansi-color-apply-on-region (point-min) (point-max)))
  :hook
  (org-mode . (lambda () ( (add-hook 'org-babel-after-execute-hook #'display-ansi-colors)))))
```

**Comment by yitang** [comment]
@Panadestein it solves the problem. thank you for your help!

**Comment by akirakyle** [comment]
This is the same issues as #380 which was fixed in [this commit](https://github.com/emacs-jupyter/jupyter/commit/053a78da252b19cf59cefe6b83f9c4531a38d6b2), so you might want to remove the work around once you upgrade past that commit.
