### ISSUE TITLE
no syntax highlighting when polymode is used

### ISSUE THREAD

**Issue by guibor** [emacs-jupyter/jupyter#479]
I use `(add-hook 'python-mode-hook 'poly-python-sql-mode)` where `poly-python-sql-mode` is a special `polymode` that correctly highlights SQL queries that are used within strings in a Python file.

When this is used, and I use `org-edit-special`, with `jupyter-python`, there is no syntax highlighting in the Python buffer (not even standard `python-mode` highlighting.

**Comment by nnicandro** [comment]
Do you have the same issue when using a regular `python` source block (not a `jupyter-python` block)?

**Comment by guibor** [comment]
Indeed, this looks like an issue with `polymode` and `org-src`, not with `jupyter`. 
Closing this. Thanks for the great package!
