### ISSUE TITLE
How can I run a REPL associated with an org-babel session?

### ISSUE THREAD

**Issue by md-zengo** [emacs-jupyter/jupyter#482]
Let's say I have

```
#+begin_src jupyter-python :session py3
import sys
sys.executable


a = 1

#+end_src
```

If I run `jupyter-run-repl` I will get a fresh REPL, is there a way to get a REPL that is associated with the session in a specific org-block?

**Comment by roblem** [comment]
for me `alt-DownArrow` works when the cursor is in the src block.

**Comment by guibor** [comment]
Thanks a lot! Can you type `C-h k` to see what function that keybinding maps to?

**Comment by guibor** [comment]
Never mind. It's `org-metadown` and that calls `org-metadown-hooks`, that include `org-babel-pop-to-session-maybe` (that is the function that gets the associated REPL).

Thanks!

**Comment by nnicandro** [comment]
The solution is to call `org-babel-pop-to-session-maybe` as has been discussed.
