### ISSUE TITLE
Image redisplay doesn't work with :async yes anymore

### ISSUE THREAD

**Issue by timlod** [emacs-jupyter/jupyter#485]
Hi,

For some time (since merge of `next` or later), images don't redisplay for me anymore, having configured `(add-hook 'org-babel-after-execute-hook 'org-redisplay-inline-images)`, which used to work fine. I've tried a variety of different ways to redisplay the images, none of which work anymore.

I always run blocks with `:async yes`, and realized that it will still work if using `:async no`, so my guess is that there was probably some regression recently with how images/image links are added after executing an async block.

**Comment by timlod** [comment]
For some additional context, I think that `org-babel-after-execute-hook` used to be called after the async execution finished, but now it appears to be called right after execution is initiated for async blocks, instead of when they return.

**Comment by MasonProtter** [comment]
I'm also experiencing this @nnicandro any ideas or suggestions?

**Comment by nnicandro** [comment]
I was able to get this working again for my setup with the change in 0480c476cb1fc3006397c6f038c75d949c9d0e64.

The hook is being called on reception of an `execute_reply` message which is basically the end of the async execution. When handling that message it wasn't guaranteed that the current buffer is the Org mode buffer containing the source block.

**Comment by timlod** [comment]
Can confirm that this fixes it - thanks!

**Comment by danielpopescu** [comment]
This is happening again, after latest jupyter update (2024/3/28) and when using emacs 30. Had to change from async yes to async no to have images displayed....
