### ISSUE TITLE
org-babel-after-execute-hook not executed in context when called from jupyter-handle-execute-reply

### ISSUE THREAD

**Issue by ahmed-shariff** [emacs-jupyter/jupyter#492]
I have a hook added to the `org-babel-after-execute-hook` which is expected to run with point at the source block. But I get the following error:
```emacs-lisp
Jupyter: I/O subscriber error: (error "‘org-element-at-point’ cannot be used in non-Org buffer #<buffer  *zmq*-120077> (special-mode)")
```

The above happens with `jupyter-python` in:
- emacs 29.1
- org mode version 9.7-pre (release_9.6.8-745-gdbf415)
- emacs-jupyter 1baabc8

Based on my exploration, the issue seems to be happening in this method:
https://github.com/emacs-jupyter/jupyter/blob/1baabc8f2d0631f8f4308400f9a53f1aadd58d14/jupyter-org-client.el#L340-L350

When the `org-babel-after-execute-hook` is called, seems like it is not being called from the context of the source block. As a workaround I have the following extension method:

```emacs-lisp
  (cl-defmethod jupyter-handle-execute-reply :around ((_client jupyter-org-client) (req jupyter-org-request) msg)
    (org-with-point-at (jupyter-org-request-marker req)
      (cl-call-next-method)))
```

**Comment by nnicandro** [comment]
Thanks, I fixed this in 0480c47.
