### ISSUE TITLE
automatic display inline image?

### ISSUE THREAD

**Issue by pcompassion** [emacs-jupyter/jupyter#509]
`(add-hook 'org-babel-after-execute-hook #'org-redisplay-inline-images 'append)`

I've tried to debug, and it seems, the hook is called with some artificial context (probably a new buffer, the (point) call returns 1

and it fails to redraw the image.

**Comment by nnicandro** [comment]
Do you have an updated version of Emacs-Jupyter that includes 0480c476cb1fc3006397c6f038c75d949c9d0e64? This issue should have been fixed by that commit.

**Comment by pcompassion** [comment]
ok... i used use-package and it doesn't fetch the one with the code you mentioned,

i'll manually pull or add the modification thanks,
it works with the modification
