### ISSUE TITLE
up arrow and down arrow key to navigate code 

### ISSUE THREAD

**Issue by Yousuf28** [emacs-jupyter/jupyter#520]
Thanks for the package. It really help set up interactive data analysis environment. 
I have one question. 
If I start IPyhton on terminal and run some code, I can navigate code history by pressing up and down arrow. 
When I start Jupyter-run-repl in emacs, which start an IPython terminal. on the IPython terminal, If I press up and down arrow, the cursor itself move up and down. 
Are there any key binding I can just go to previous code chunk?

Thanks

**Comment by nnicandro** [comment]
You can use `M-n` and `M-p` in the REPL buffer to navigate code chunks in the REPL history.

**Comment by Yousuf28** [comment]
thanks @nnicandro
