### ISSUE TITLE
Enable Github Discussions 

### ISSUE THREAD

**Issue by MasonProtter** [emacs-jupyter/jupyter#521]
It'd be nice if someone with rights could [enable Github Discussions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository) here, as I'm not really aware of any dedicated forums where one can get help or discuss things related to emacs-jupyter which don't narrowly fit into the `issues` tracker.

**Comment by nnicandro** [comment]
Thanks for the suggestion. I enabled it.
