### ISSUE TITLE
make test

### ISSUE THREAD

**Issue by badkey** [emacs-jupyter/jupyter#533]
I tried to run the test of the project. After installing cask, I tried make dev - it finds not target.

I tried make test as follows:

: make test
: test 
: make: *** [Makefile:33: test] Fehler 1

Looking at line 33 I installed eldev (https://github.com/doublep/eldev)

curl -fsSL https://raw.github.com/emacs-eldev/eldev/master/webinstall/eldev | sh

which made the test possible. So this hint might be added to the documentation.

**Comment by nnicandro** [comment]
Thanks, I transitioned over to eldev and forgot to update the documentation.
