### ISSUE TITLE
DataFrame with Index name not displaying well in org mode

### ISSUE THREAD

**Issue by WillAyd** [emacs-jupyter/jupyter#548]
Thanks for the great library. I am not well versed in all of the inner workings here and this issue might fall into a gray area, so apologies if its not something the library can handle.

I am trying to figure out the best way to render a pd.DataFrame which happens to have an index name in an org file. A MRE with output looks something like:

```sh
#+BEGIN_SRC jupyter-python :exports both value :session py :async yes
  df = pd.DataFrame([[1]], columns=["a"], index=pd.Index([42], name="index"))
  df
#+END_SRC

#+RESULTS:
#+begin_export html
<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>a</th>
    </tr>
    <tr>
      <th>index</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>42</th>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>
#+end_export
```

As you can see, the table header actually ends up with two rows, which you can see when running in jupyter directly:

![image](https://github.com/user-attachments/assets/7f4612c1-9475-4b3a-bdbc-e63797c65bc2)

Adding `:pandoc t` to the source block really throws a wrench into the output:

```
#+BEGIN_SRC jupyter-python :exports both value :session py :async yes :pandoc t
  df = pd.DataFrame([[1]], columns=["a"], index=pd.Index([42], name="index")) 
  df
#+END_SRC

#+RESULTS:
:RESULTS:
a
index
42
1
:END:
```

I assume this is because pandoc does not generically know how to convert multiple header rows from HTML into a single row for org-mode, which makes sense.

Is there a clever way to get this to render in org?

**Comment by pati-ni** [comment]
Hi @WillAyd,

Do you have pandoc installed in your system and added to your $PATH?

**Comment by WillAyd** [comment]
Yes I have 2.9.2 installed on my system. It works great for DataFrames so long as there is no index name

**Comment by gmoutso** [comment]
I assume you want an org-mode table rather than html or latex. The fastest way is to return `df.reset_index()`! This is probably the _cleverest_. There will be two issues: 1) It will work until you have multiindex columns (but does work with multiindex index). 2) The reset index will also display a new index, which is probably useless. One way to not display the new index is to use the `tabulate` module with `showindex=False`. But `tabulate` also has problems with multiindex columns, where these are passed in `headers=df.columns` of tabulate.

I am not sure if pandoc can produce the org-mode table in the simple example of an index with a name. I have a solution [here](https://gist.github.com/gmoutso/4448ff9cd70a9381c20f016dad74b72e) that solves the index name and multiindex column issue. It involves parsing the org-mode table from inside ipython using the mime org/text that emacs-jupyter recognises. It has taken some liberties, eg. it inserts horizontal and vertical lines only once each to seperate index, columns and values, the /,<,> org-table groups, which are exported nicely to html/latex. It also does not repeat index/column values in a multiindex. And most importantly it prints only index names but not column names. Any improvements are welcome.

```
#+begin_src jupyter-python
import pandas as pd
from itertools import product
# from tabulate import tabulate
df = pd.DataFrame(1,
             columns=pd.MultiIndex.from_tuples(product("AB","CD"), names=["CName1", "CName2"]),
             index=pd.MultiIndex.from_tuples(product(range(2), range(2)), names=["IName1", "IName2"])
                  )
df
#+end_src

#+RESULTS:
|        |        | A |   | B |   |
| IName1 | IName2 | C | D | C | D |
|--------+--------+---+---+---+---|
|   /    |        | < |   |   |   |
|   0    |   0    | 1 | 1 | 1 | 1 |
|        |   1    | 1 | 1 | 1 | 1 |
|   1    |   0    | 1 | 1 | 1 | 1 |
|        |   1    | 1 | 1 | 1 | 1 |

```

**Comment by WillAyd** [comment]
@gmoutso thanks for the feedback. You are correct that I am looking for an org-mode table

> The fastest way is to return `df.reset_index()`! This is probably the _cleverest_.

For sure. The main problem with this approach is that I am using org-mode to author a book, so adding in extraneous method calls to improve formatting is a tough compromise to make

Your workaround is pretty interesting though - it does seem to provide an org-table output closer to what I am looking for. Let me experiment some more with that and post back any findings.

Really appreciate the response

**Comment by WillAyd** [comment]
I do see that it rather significantly slows down the org file execution. Does that formatting get applied to the entire DataFrame even if only a few rows actually get printed out?

**Comment by gmoutso** [comment]
The formatter will apply to the whole dataframe and the whole is what will be printed in the org file. I don't think it would be a big overhead in time! Bear in mind I only present tables that are meant to be displayed in one page, or a few pages and use the latex `longtable` package on export. Also, I evaluate my blocks interactively and code is not evaluated on export, by using the `:eval never-export` as default. 

The code in the gist could be made faster, but how slow is it in your case? Can you elaborate on your workflow, for instance you mentioned writing a book so will you be exporting the org file to pdf or html? How big are the tables? Do you eval in export and can you measure the time difference?

If the table is massive and you only want to print a summary of the table and don't mind not using an org table, you could print the dataframe. You can even control how much is printed like this:

```python
with pd.option_context(
        "display.max_rows", 20,
        "display.min_rows", 10,
        "display.show_dimensions", False
):
    print(df)
```

Note that the above prints a verbatim summary and not an org-mode table. 

Ultimately the issue you described in the beginning is a bug of pandoc. Other ways, which I have not pursued, would be to see if "df.style" or "df.to_csv" can be used to print an org-mode table in the buffer in these situations. Another idea, if your table is massive, would be to save the table as a csv file and have a method of making it visible on export by using a latex package / html js.

**Comment by gmoutso** [comment]
> Ultimately the issue you described in the beginning is a bug of pandoc.

This didn't sound right to me. I had version pandoc 2.1 so I tried [try pandoc online](https://pandoc.org/try/) with the following
```html
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
    </tr>
    <tr>
      <th>a</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1.2</td>
    </tr>
  </tbody>
</table>
```
and it produces a good org-table. Saved to a file and using my installed pandoc it failed like in your original example. Upgrading to pandoc 3.2.1 (I used conda-forge), the pandoc command gives the good table like the online version.
```org
|   | A   |
|---+-----|
| a |     |
| 0 | 1.2 |
```
