### ISSUE TITLE
Source block stuck being executed after kernel has been shut down or changed

### ISSUE THREAD

**Issue by mochar** [emacs-jupyter/jupyter#560]
Specifically I encounter this problem when using a remote kernel like so: `:session /jpy:localhost#8888:name`.

After shutting down the kernel, or trying to connect to a new one, and sometimes even spuriously while running some code blocks, the package thinks a source block is still in the middle of being executed and I loose the ability to run that block (while still being able to run others). 

Closing the file doesn't help, the only thing I can do is restart emacs.

Any tips? Thanks!

**Comment by fraricci** [comment]
Hey! I think the answer is here #538

**Comment by mochar** [comment]
> Hey! I think the answer is here #538

Awesome thank you for informing me! Then I'll close this issue since that one exist already.
